config/routes.rb
Jimmy::Application.routes.draw do

  resources :posts

  root :to => "groups#index"

  devise_for :users

  resources :groups do
    member do
      get 'info'
    end

    collection do
      get 'search'
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base

	validates :title, :presence => true

	# {:key => 'value'} 
	# {key: 'value'} # Ruby 1.9+

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :info]
  before_action :set_group, only: [:info, :show, :destroy, :update, :edit]

  def info
  end

	def index
		@group = Group.all
		##render :action=> 'index1'
	end

	def show
	end

	def destroy
		@group.destroy
		redirect_to groups_path
	end

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_params)
		if @group.save
			redirect_to groups_path
		else
			render :new
			# =>render :action=> 'index1'
		end
	end

	def edit
	end

	def update
		if @group.update(group_params)
			redirect_to groups_path
		else
			render :edit
		end
	end

  private
  	def group_params
  		params.require(:group).permit(:title, :description)
  	end

    def set_group
      @group = Group.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/groups/edit.html.erb
<h1>Edit page</h1>
<div class="container">
  <%= simple_form_for @group do |f| %>
    <% if @group.errors.any?%>
    	<h4>Errors</h4>
    <%end%>
    <%= f.input :title %>
    <%= f.input :description%>
    <%=f.submit 'Save'%>
  <%end%>
</div>

app/views/groups/index.html.erb
<h1>index page</h1>

<%= link_to "新增",new_group_path%>
<table class="table">
<tr>
	<td>Title</td>
	<td>Description</td>
	<td>Action</td>
</tr>

<%@group.each do |group|%>
	<tr>
	<td><%=group.title%> </td>
	<td><%=group[:description]%></td>
	<td>
    <!-- Info Link -->
    <%= link_to "Info訊息", info_group_path(group), class: 'btn btn-primary' %>
		<!-- Show Link -->
		<%= link_to "show1", group_path(group), class: 'btn btn-info' %>
		<%= link_to "show2", group_path(group.id), class: 'btn btn-info' %>
		<%= link_to "show3", group, class: 'btn btn-info' %>

		<!-- Edit Link -->
		<%= link_to "修改1", edit_group_path(group), class: 'btn btn-warning' %>

		<%= link_to "修改2", edit_group_path(group.id), class: 'btn btn-warning' %>

		<!-- Delete Link -->
		<%= link_to "刪除", group_path(group.id), :method => 'delete', :confirm => 'are you sure!', class: 'btn btn-danger' %>
	</td>
</tr>

<%end%>

</table>

app/views/groups/index1.html.erb
index1 page

app/views/groups/info.html.erb
<h3>Info</h3>

app/views/groups/new.html.erb
<div class="container">
  <h1>new page</h1>
  <%= simple_form_for(@group, html: {class: 'form-horizontal' }) do |f| %>
    <% if @group.errors.any?%>
      <h4>Errors</h4>
    <%end%>
    <%= f.input :title %>
    <%= f.input :description%>
    <%=f.submit 'Save'%>
  <%end%>
</div>

app/views/groups/show.html.erb
<h1>Show page</h1>
<%= link_to "回清單",groups_path%>

<br><br><br>
Title:
<%= @group.title %>
<hr>
Description:
<%= @group.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jimmy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice.present? %>
    <div class="alert alert-success">
      <strong>Notice!</strong>
      <%= notice %>
    </div>
  <% end %>
  <% if alert.present? %>
    <div class="alert alert-danger">
      <strong>Alert!</strong>
      <%= alert %>
    </div>
  <% end %>

  <div class="container">
    <%= link_to '回首頁', root_path, class: 'btn btn-danger' %>
    <% if user_signed_in? %>
      <%= "#{current_user.email} 你好!" %>
      <%= link_to '登出', destroy_user_session_path, method: 'DELETE', confirm: '確定登出', class: 'btn btn-danger' %>
    <% else %>
      <%= link_to '登入', new_user_session_path, class: 'btn btn-danger' %>
      <%= link_to '註冊', new_user_registration_path, class: 'btn btn-danger' %>
    <% end %>
    <%= link_to '留言板', posts_path, class: 'btn btn-info' %>
    <div class="span12">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Post By:</strong>
  <br>
  <%= @post.user.email %>
  <br>
  <%= @post.user.created_at %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>